version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  
    restart: unless-stopped


  cloak-server:
    image: ghcr.io/dobbyvpn/dobbyvpn-server/cloak-server:latest
    command: ["/app/ck-server", "-c", "/app/config.json"]
    restart: always
    network_mode: "host"
    volumes:
      - ./cloak-server.conf:/app/config.json
