version: '3.8'

services:
  caddy:
    image: caddy:2.8.4
    container_name: caddy
    network_mode: "host"
    volumes:
      - ./data/Caddyfile:/etc/caddy/Caddyfile  
    restart: always


  cloak-server:
    image: ghcr.io/dobbyvpn/dobbyvpn-server/cloak-server:v2.10.0.3
    container_name: ck-server
    entrypoint: ["/app/data/cloak_start.sh"]  
    network_mode: "host"
    volumes:
      - ./data:/app/data
    restart: always
