version: '3.8'

services:
  caddy:
    image: caddy:2.8.4
    container_name: caddy
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  
    restart: always


  cloak-server:
    image: ghcr.io/dobbyvpn/dobbyvpn-server/cloak-server:v2.10.0
    container_name: ck-server
    entrypoint: ["/app/data/cloak_start.sh"]  
    network_mode: "host"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - /root/dobbyvpn-server/data/:/app/data/
    restart: always

  shadowbox:
    image: quay.io/outline/shadowbox:stable
    container_name: shadowbox
    network_mode: "bridge"
    ports:
      - 127.0.0.1:<outline-api-port>:<outline-api-port>
      - 127.0.0.1:<outline-keys-port>:<outline-keys-port>

    environment:
      - SB_STATE_DIR=/opt/outline/persisted-state
      - SB_API_PORT=<outline-api-port>
      - SB_API_PREFIX=<outline-api-prefix>
      - SB_CERTIFICATE_FILE=/opt/outline/persisted-state/shadowbox-selfsigned.crt
      - SB_PRIVATE_KEY_FILE=/opt/outline/persisted-state/shadowbox-selfsigned.key
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - /opt/outline/persisted-state:/opt/outline/persisted-state
    restart: "always"

  awg-server:
    image: ghcr.io/dobbyvpn/dobbyvpn-server/awg-server:v0.2.12.21
    container_name: awg-server
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - ./awg-entrypoint.sh:/awg/awg-entrypoint.sh
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: "always"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: "host"
    depends_on:
      - caddy
      - cloak-server
      - shadowbox
        #     - awg-server
    command:
      - "--cleanup"
      - "--label-enable"
      - "--interval"
      - "30"
    labels:
      com.centurylinklabs.watchtower: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "always"
