networks:
  caddy_cloak_ss_network:
    driver: bridge

services:
  caddy_outline:
    image: caddy:2
    container_name: caddy_outline
    profiles: ["outline"]
    networks:
      - caddy_cloak_ss_network
    ports:
      - 443:443/tcp
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CLOAK_SECRET=${CLOAK_SECRET}
      - CLOAK_SERVER_PORT=${CLOAK_SERVER_PORT}
    volumes:
      - ./caddy/Caddyfile_outline:/etc/caddy/Caddyfile  
      - ./caddy/data:/data
      - ./caddy/config:/config
    restart: unless-stopped

  cloak-server:
    image: ghcr.io/dobbyvpn/dobbyvpn-server/cloak-server:v2
    container_name: ck-server
    profiles: ["outline"]
    networks:
      - caddy_cloak_ss_network
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - ./cloak/cloak-server.conf:/app/cloak-server.conf
    entrypoint: |
      sh -c "exec /app/ck-server -c /app/cloak-server.conf"
    restart: unless-stopped

  shadowbox:
    image: quay.io/outline/shadowbox:stable
    container_name: shadowbox
    profiles: ["outline"]
    networks:
      - caddy_cloak_ss_network
    ports:
      - 127.0.0.1:${OUTLINE_API_PORT:-11111}:${OUTLINE_API_PORT:-22222} 
    environment:
      - SB_STATE_DIR=/opt/outline/persisted-state
      - SB_API_PORT=${OUTLINE_API_PORT}
      - SB_API_PREFIX=${OUTLINE_API_PREFIX}
      - SB_CERTIFICATE_FILE=/opt/outline/persisted-state/shadowbox-selfsigned.crt
      - SB_PRIVATE_KEY_FILE=/opt/outline/persisted-state/shadowbox-selfsigned.key
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - /opt/outline/persisted-state:/opt/outline/persisted-state
    restart: unless-stopped

  awg-server:
    image: ghcr.io/dobbyvpn/dobbyvpn-server/awg-server:v0.2
    container_name: awg-server
    profiles: ["awg"]
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    network_mode: "bridge"
    ports:
      - "51820:51820/udp"
    volumes:
      - /lib/modules:/lib/modules
      - ${PWD}/awg:/etc/amnezia/amneziawg
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    devices:
      - /dev/net/tun
    restart: unless-stopped

  xray-server:
    image: teddysun/xray:24.12.31
    container_name: xray-server
    profiles: ["xray"]
    ports:
      - 443:443
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - XRAY_CLIENT_UUID=${XRAY_CLIENT_UUID}
    volumes:
      - ./xray:/etc/xray   # For xray config
      - ${CERT_DIR}:/root  # For TLS cert files created by Caddy
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    entrypoint: |
      sh -c "exec /usr/bin/xray -config /etc/xray/config.json"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    profiles: ["outline", "awg", "xray"]
    network_mode: "bridge"
    command:
      - "--cleanup"
      - "--label-enable"
      - "--interval"
      - "30"
    labels:
      com.centurylinklabs.watchtower: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
