services:

  shadowbox:
    command:
      - "/cmd.sh"
    container_name: "shadowbox"
    entrypoint:
      - "docker-entrypoint.sh"
    environment:
      - "NODE_VERSION=18.18.0"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "SB_API_PORT=11111"
      - "SB_CERTIFICATE_FILE=/opt/outline/persisted-state/shadowbox-selfsigned.crt"
      - "SB_METRICS_URL="
      - "SB_PRIVATE_KEY_FILE=/opt/outline/persisted-state/shadowbox-selfsigned.key"
      - "SB_STATE_DIR=/opt/outline/persisted-state"
      - "YARN_VERSION=1.22.19"
    image: "quay.io/outline/shadowbox:stable"
    ipc: "private"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      shadowbox.github.release: "1.11.0"
      shadowbox.node_version: "16.18.0"
    logging:
      driver: "local"
      options: {}
    network_mode: "host"
    restart: "always"
    volumes:
      - "/opt/outline/persisted-state:/opt/outline/persisted-state"
    working_dir: "/opt/outline-server"

  watchtower:
    command:
      - "--cleanup"
      - "--label-enable"
      - "--tlsverify"
      - "--interval"
      - "3600"
    container_name: "watchtower"
    entrypoint:
      - "/watchtower"
    environment:
    expose:
      - "8080/tcp"
    image: "containrrr/watchtower"
    ipc: "private"
    labels:
      com.centurylinklabs.watchtower: "true"
    logging:
      driver: "local"
      options: {}
    mac_address: "02:42:ac:11:00:02"
    network_mode: "bridge"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/"

version: "3.6"
