permissions:
  packages: write
  contents: write

name: Build and Push Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  build-and-push-cloak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setting Cloak version
        run: |
          git clone https://github.com/cbeuw/Cloak.git
          cd Cloak
          CLOAK_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "CLOAK_VERSION=$CLOAK_VERSION"
          echo "CLOAK_VERSION=$CLOAK_VERSION" >> $GITHUB_ENV

      - name: Build and Publish latest Docker cloak image
        uses: DrSkunk/gp-docker-action@1.1.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: cloak-server
          dockerfile: Dockerfile-cloak-server
          image-tag: ${{ env.CLOAK_VERSION }}.${{ github.run_number }}

  build-and-push-awg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: amnezia-vpn/amneziawg-go

      - name: Setting AWG version
        run: |
          ls
          pwd
          AWG_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "AWG_VERSION=$AWG_VERSION"
          echo "AWG_VERSION=$AWG_VERSION" >> $GITHUB_ENV

      - name: Build and Publish latest Docker AWG image
        uses: DrSkunk/gp-docker-action@1.1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image-name: awg-server
          dockerfile: Dockerfile
          image-tag: ${{ env.AWG_VERSION }}.${{ github.run_number }}
