permissions:
  packages: write
  contents: read

name: Build and Push Docker Image(NEW)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Finding Cloak version
        run: |
          git clone https://github.com/cbeuw/Cloak.git
          cd Cloak
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "CLOAK_VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Publish latest Docker image
        uses: DrSkunk/gp-docker-action@1.1.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: cloak-server
          dockerfile: Dockerfile-cloak-server
          image-tag: ${{ env.VERSION }}
